Merge wait for snaps and debs
canonical/hwcert-jenkins-tools pull request #11
Opened 2024-01-30 16:38 UTC by fernando79513

## Description

Merged the scripts to check if a specific snap and deb package is already published into "checkbox_version_published.py.

## Resolved issues

[Merge wait for snaps and wait for debs scripts](https://warthogs.atlassian.net/browse/CHECKBOX-1216)

## Documentation

Added a readme to the "version_published" folder

## Tests
To run the tests:
```
cd version_published
pytest 
```

2024-02-14 14:32 UTC, kissiel requested changes
TYVM! Almost there, some improvements suggestions inline

2024-02-14 14:32 UTC, kissiel commented on version-published/checkbox_version_published.py
> +    if "required-packages" not in yaml_content:
we expect the yaml to be structured as a dict, so if we actually codify it (see below for details) then we can streamline the whole thing here to just do:

`yaml_content.get("required_packages", [])`
This way no need for branching.

Same goes for snaps ofc.

2024-02-14 14:32 UTC, kissiel commented on version-published/checkbox_version_published.py
> +    yaml_content = yaml.load(args.checkbox_yaml, Loader=yaml.FullLoader)
If the yaml is empty, the loader will return None and the code will crash, it may be worth checking if it's a dict.

2024-02-14 14:35 UTC, fernando79513 commented on version-published/checkbox_version_published.py
> +    --snaps checkbox-canary-snaps.yaml
Yes, I forgot to change the docstring, I will also update it

2024-02-14 17:11 UTC, fernando79513 commented
I applied the comments you suggested. I also modified a bit the structure of the packages yaml so its more similar to the snaps one, moving the `channel` to each package, so I don't have to deal with a different lists/dicts structure.
I also updated the tests accordingly.

2024-02-16 07:24 UTC, kissiel approved these changes
Great stuff, thanks for all the tweaks!

2024-02-16 07:24 UTC, merged