Add password authentication to ssh-related scriplets
canonical/hwcert-jenkins-tools pull request #56
Opened 2024-12-05 14:54 UTC by p-gentili

Added support for password based SSH authentication, using the optional `DEVICE_PWD` env variable. 

Also, removed the `_run_zapper` since it's now redundant.

A successful test run: https://testflinger.canonical.com/jobs/c807683d-53bb-41a1-bfbb-c918ec98ce29

2024-12-09 14:05 UTC, boukeas requested changes
This looks great.

I don't think `check_for_device_ip` should be empty though, perhaps its contents were removed by mistake?

Also, could you please include a run each of one regular SRU and snap-testing job, modified to install the tools from this branch? Just as additional confirmation that nothing already in place is broken.

2024-12-09 14:24 UTC, p-gentili commented on scriptlets/defs/check_for_device_ip
ehehe it's still there, but executable. I need it to be like that so that I can run it without sourcing it, [here](https://github.com/canonical/hwcert-jenkins-tools/blob/1dcd28857e5bb5081fdf9d8a8ed991706095bcc1/scriptlets/refresh_zapper_if_needed#L34). We discussed about something similar [here](https://github.com/canonical/hwcert-jenkins-tools/pull/44#discussion_r1778728220)

2024-12-09 15:56 UTC, p-gentili commented
snap-testing job: https://testflinger.canonical.com/jobs/d8c097e4-2515-421b-bc56-23aa44fa780d

2024-12-12 11:24 UTC, boukeas commented on scriptlets/defs/check_for_device_ip
@p-gentili I am terribly sorry for being pedantic but there is really no point to keeping `check_for_device_ip` in `defs`, which is supposed to be for scripts to be sourced -- this is my fault, it should have been moved over before. I think we should move it outside, along with the other scriptlets, and run it directly in `_run`, `_get` and `_put` instead of sourcing it. Would you mind doing that triggering a test run?

2024-12-12 11:27 UTC, boukeas commented on scriptlets/defs/check_for_device_ip
Detail: if it's in scriptlets, we can just run it as `check_for_device_ip`, since it will be in the PATH.

2024-12-12 11:32 UTC, boukeas commented on scriptlets/defs/check_for_device_ip
I think that in `_run`, `_get` and `_put`, the corresponding line would become `check_for_device_ip || exit 1`

2024-12-18 15:30 UTC, p-gentili commented
Re-run a snap job: https://testflinger.canonical.com/jobs/b4174d47-f186-42fc-9d23-6ad25d2a70c9

2024-12-18 16:49 UTC, p-gentili commented
And SRU: https://testflinger.canonical.com/jobs/a2dfdce1-9e3d-4460-927e-6040f32826d0

2024-12-20 12:29 UTC, boukeas approved these changes
+1

You might want to consider a comment I've made in `_run`, `_get` and `_put` about using variable substitution to set `SSHPASS`

2025-01-07 09:46 UTC, p-gentili commented
A quick test to validate https://github.com/canonical/hwcert-jenkins-tools/pull/56/commits/8e20c3995abc933104464ad00d724134e299b832 : https://testflinger.canonical.com/jobs/1b62dfa9-1017-4e96-9b80-6ff564936833

2025-01-07 09:46 UTC, merged